"Locker"
{
    "mg_swag_multigames_v7_nc2"
    {
        "0"
        {
            "HammerId" "456753"
            "Cooldown" "600"
            "Name"     "足球小游戏"
        }
    }
    "mg_quepinator"
    {
        "0"
        {
            "HammerId" "77590"
            "Cooldown" "300"
            "Name"     "莫洛托夫"
        }
    }
    "mg_mario_party_v3_1"
    {
        "0"
        {
            "HammerId" "28389"
            "Cooldown" "600"
            "Name"     "红黄测试"
        }
    }
}