"Buttons"
{
	// enum /* mode_t */

    // Game_Invalid      = -1,
    // Game_Guns         = 0, // 对枪
    // Game_Nade         = 1, // 手雷
    // Game_Knife        = 2, // 拼刀
    // Game_Taser        = 3, // 电击枪
    // Game_Dodgeball    = 4, // 躲避球
    // Game_RaceCombat   = 5, // Race给枪    LongJump, Bhop, Race, Clmib, Combat
    // Game_RaceBonus    = 6, // Race刷分    LongJump, Bhop, Race, Clmib, 刷分
    // Game_Survival     = 7, // 生存        JumpRope, FallingBox etc...
    // Game_RaceSurvival = 8, // Race生存    LongJump, Bhop, Race, Clmib, Survival

	// mode要选好对应的 
	// name显示对应的游戏模式 

	"0"
	{
		"id"		"264852"
		"cd"        "0"
		"mode"		"0"
		"name"		"AWP"
	}
	"1"
	{
		"id"		"25693"
		"cd"        "0"
		"mode"		"0"
		"name"		"AWP"
	}
	"2"
	{
		"id"		"264821"
		"cd"        "0"
		"mode"		"0"
		"name"		"AWP"
	}
	"3"
	{
		"id"		"142137"
		"cd"        "0"
		"mode"		"0"
		"name"		"AWP"
	}
	"4"
	{
		"id"		"76400"
		"cd"        "0"
		"mode"		"0"
		"name"		"AWP"
	}
	"5"
	{
		"id"		"49233"
		"cd"        "0"
		"mode"		"0"
		"name"		"AWP"
	}
	"6"
	{
		"id"		"37620"
		"cd"        "0"
		"mode"		"0"
		"name"		"AWP"
	}
	"7"
	{
		"id"		"73068"
		"cd"        "0"
		"mode"		"0"
		"name"		"AWP"
	}
	"8"
	{
		"id"		"82793"
		"cd"        "0"
		"mode"		"0"
		"name"		"AWP"
	}
	"9"
	{
		"id"		"12589"
		"cd"        "0"
		"mode"		"0"
		"name"		"AWP"
	}
	"10"
	{
		"id"		"179074"
		"cd"        "0"
		"mode"		"0"
		"name"		"AWP"
	}
	"11"
	{
		"id"		"26947"
		"cd"        "0"
		"mode"		"0"
		"name"		"AWP"
	}
}
