"Buttons"
{
    // enum /* mode_t */

    // Game_Invalid      = -1,
    // Game_Guns         = 0, // 对枪
    // Game_Nade         = 1, // 手雷
    // Game_Knife        = 2, // 拼刀
    // Game_Taser        = 3, // 电击枪
    // Game_Dodgeball    = 4, // 躲避球
    // Game_RaceCombat   = 5, // Race给枪    LongJump, Bhop, Race, Clmib, Combat
    // Game_RaceBonus    = 6, // Race刷分    LongJump, Bhop, Race, Clmib, 刷分
    // Game_Survival     = 7, // 生存        JumpRope, FallingBox etc...
    // Game_RaceSurvival = 8, // Race生存    LongJump, Bhop, Race, Clmib, Survival
    // Game_Asymmetric   = 9, // 非对称      Submarine, Fat, Zombie

    // mode要选好对应的 
    // name显示对应的游戏模式 

    "1"
    {
        "id"    "666382"
        "cd"    "235"
        "mode"  "4"
        "name"  "躲避球"
        "class" "func_button"
        "event" "OnPressed"
    }

    "2"
    {
        "id"    "589994"
        "cd"    "235"
        "mode"  "0"
        "name"  "鸟狙"
        "class" "func_button"
        "event" "OnPressed"
    }

    "3"
    {
        "id"    "599958"
        "cd"    "235"
        "mode"  "0"
        "name"  "大狙"
        "class" "func_button"
        "event" "OnPressed"
    }

    "4"
    {
        "id"    "1006379"
        "cd"    "235"
        "mode"  "2"
        "name"  "溜冰"
        "class" "func_button"
        "event" "OnPressed"
    }

    "5"
    {
        "id"    "163329"
        "cd"    "235"
        "mode"  "2"
        "name"  "35hp刀"
        "class" "func_button"
        "event" "OnPressed"
    }

    "6"
    {
        "id"    "48697"
        "cd"    "235"
        "mode"  "0"
        "name"  "拆墙"
        "class" "func_button"
        "event" "OnPressed"
    }

    "7"
    {
        "id"    "45428"
        "cd"    "235"
        "mode"  "1"
        "name"  "高爆手雷"
        "class" "func_button"
        "event" "OnPressed"
    }

    "8"
    {
        "id"    "34606"
        "cd"    "999"
        "mode"  "6"
        "name"  "连跳"
        "class" "func_button"
        "event" "OnPressed"
    }

    "9"
    {
        "id"    "169097"
        "cd"    "999"
        "mode"  "6"
        "name"  "攀登"
        "class" "func_button"
        "event" "OnPressed"
    }

    "10"
    {
        "id"    "179016"
        "cd"    "235"
        "mode"  "7"
        "name"  "我说你做"
        "class" "func_button"
        "event" "OnPressed"
    }

    "11"
    {
        "id"    "585367"
        "cd"    "235"
        "mode"  "0"
        "name"  "沙鹰爆头"
        "class" "func_button"
        "event" "OnPressed"
    }

    "12"
    {
        "id"    "604349"
        "cd"    "999"
        "mode"  "6"
        "name"  "竞速"
        "class" "func_button"
        "event" "OnPressed"
    }

    "13"
    {
        "id"    "633582"
        "cd"    "235"
        "mode"  "0"
        "name"  "自由战"
        "class" "func_button"
        "event" "OnPressed"
    }

}
