"Buttons"
{
    // Button configuration file generator.
    // Copyright 2022 Kyle 'Kxnrl' Frankiss 
    // https://github.com/fys-csgo/Server-Configs-Generator


    "1"
    {
        "id"    "666382"
        "cd"    "360"
        "mode"  "4"
        "name"  "躲避球"
    }

    "2"
    {
        "id"    "589994"
        "cd"    "360"
        "mode"  "0"
        "name"  "鸟狙"
    }

    "3"
    {
        "id"    "599958"
        "cd"    "360"
        "mode"  "0"
        "name"  "大狙"
    }

    "4"
    {
        "id"    "1006379"
        "cd"    "360"
        "mode"  "2"
        "name"  "溜冰"
    }

    "5"
    {
        "id"    "163329"
        "cd"    "360"
        "mode"  "2"
        "name"  "35hp刀"
    }

    "6"
    {
        "id"    "48697"
        "cd"    "360"
        "mode"  "0"
        "name"  "拆墙"
    }

    "7"
    {
        "id"    "45428"
        "cd"    "360"
        "mode"  "1"
        "name"  "高爆手雷"
    }

    "8"
    {
        "id"    "34606"
        "cd"    "360"
        "mode"  "6"
        "name"  "连跳"
    }

    "9"
    {
        "id"    "169097"
        "cd"    "360"
        "mode"  "6"
        "name"  "攀登"
    }

    "10"
    {
        "id"    "179016"
        "cd"    "360"
        "mode"  "7"
        "name"  "我说你做"
    }

    "11"
    {
        "id"    "585367"
        "cd"    "360"
        "mode"  "0"
        "name"  "沙鹰爆头"
    }

    "12"
    {
        "id"    "604349"
        "cd"    "360"
        "mode"  "6"
        "name"  "竞速"
    }

    "13"
    {
        "id"    "633582"
        "cd"    "360"
        "mode"  "0"
        "name"  "自由战"
    }

}